config/routes.rb
Rails.application.routes.draw do
  resources 'contacts', only: [:new, :create], path_names: { new: '' }
  

  mount LetterOpenerWeb::Engine, at: "/letter_opener"

  mount Ckeditor::Engine => '/ckeditor'
  
  resources :events do
    get :get_events, on: :collection
  end
  devise_for :users
  
  get "/pages/:page" => "pages#show"
  
  get "/services" => "pages#services"
  
  root "pages#show", page: "home"
  
  resources :images
  
  get "/animal" => "images#animal"
  get "/flower" => "images#flower"
  get "/sun" => "images#sun"
  get "/coast" => "images#coast"
  get "/water" => "images#water"
  get "/cloud" => "images#cloud"
  get "/portfolio" => "images#portfolio"
  
  
  resources :videos, only: [:index, :new, :create, :destroy]
  
  resources :messages

  resources :posts
  
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/contact.rb
class Contact < MailForm::Base
  append :remote_ip, :user_agent
  attribute :name,      validate: true
  attribute :email,     validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  validates :message,   length: { in: 15..2000 }

  def headers
    {
      subject: 'Contact Form',
      to: 'edicristoforo@gmail.com',
      from: %("#{name}" <#{email}>)
    }
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
    validates :i, presence: true
    validates :caption, presence: true
    validates :category, presence: true

    
    has_attached_file :i, styles: {:medium => "640x" }
    validates_attachment_content_type :i, 
        :content_type => [/\Aimage\/.*\Z/, 'video/mp4']
    
    belongs_to :user
    
    
    
end

app/models/message.rb
class Message
    include ActiveModel::Model
    attr_accessor :name, :email, :body
    validates :name, :email, :body, presence: true
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
    validates :title, presence: true, length: {maximum: 140}
    validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  extend Devise::Models
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :posts, dependent: :destroy

end

app/models/video.rb
class Video < ActiveRecord::Base
    YT_LINK_FORMAT = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i
    validates :link, presence: true, format: YT_LINK_FORMAT
end

app/models/video_observer.rb
class VideoObserver < ActiveRecord::Observer
  def before_save(resource)
    video = Yt::Video.new url: resource.link
    resource.uid = video.id
    # resource.title = video.title
    # resource.likes = video.like_count
    # resource.dislikes = video.dislike_count
    # resource.published_at = video.published_at
  rescue Yt::Errors::NoItems
    resource.title = ''
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver 
      flash.now[:error] = nil
      flash.now[:notice] = 'Thank you for your message!'
    else
      flash.now[:error] = ' Cannot send message at this time'
      render :new
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
    
    def index
        @images = Image.all
    end
    
    # actions for every category
    def animal
        @images = Image.where(:category => "Animals")
    end
    
    def flower
        @images = Image.where(:category => "Flowers")
    end
    
    def sun
        @images = Image.where(:category => "Sunrises/Sunsets")
    end
    
    def coast
        @images = Image.where(:category => "Coastal Areas")
    end
        
    def water
        @images = Image.where(:category => "Lakes and Rivers")
    end
            
    def cloud
        @images = Image.where(:category => "Clouds")
    end
    
    def portfolio
        @images = Image.where(:category => "Portfolios")
    end
    

    
    def new
        @image = Image.new
    end
    
    def create
        @image = Image.create(post_params)
        
        if @image.save
            flash[:notice] = "Successfully created image!"
            redirect_to images_path
        else
            flash[:alert] = "Error creating new image!"
            render :new
        end
    end
    
    def destroy
        @image = Image.find(params[:id])
        @image.destroy
        redirect_to images_path
    end
    
    def show
        @image = Image.find(params[:id])
    end
    
    def edit
        @image = Image.find(params[:id])
    end
    
    def update 
        @image = Image.find(params[:id])
        @image.update(post_params)
        redirect_to(image_path(@image))
    end
    
    private 
    
    def post_params
        params.require(:image).permit(:i, :caption, :category)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def new
        @message = Message.new
    end

  def create
    @message = Message.new message_params

    if @message.valid?
      MessageMailer.contact_me(@message).deliver_now
      redirect_to new_message_url, notice: "Message received, thanks!"
    else
      flash[:notice] = "There was an error sending your message, please try again!"
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :body)
  end  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def show
        render template: "pages/#{params[:page]}"
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:edit, :update, :show, :delete]
    
    def index
        @posts = Post.all
    end
    
    def new 
        @post = Post.new
    end
    
    def create
        @post = Post.new(post_params)
        if @post.save
            flash[:notice] = "Successfully created post!"
            redirect_to post_path(@post)
        else
            flash[:alert] = "Error creating new post!"
            render :new
        end
    end
    
    def edit
    end
    
    def update
        if @post.update_attributes(post_params)
            flash[:notice] = "Successfully updated post!"
             redirect_to post_path(@posts)
        else
            flash[:alert] = "Error updating post!"
            render :edit
        end
    end
    
    def show
    end
    
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end
    
    private
    
    def post_params
        params.require(:post).permit(:title, :body)
    end
    
    def find_post 
        @post = Post.find(params[:id])
    end
    
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
    def index
        @videos = Video.order('created_at DESC')
    end

    def new
        @video = Video.new
    end

    def create
        @video = Video.new(video_params)
        if @video.save
            flash[:success] = 'Video added!'
            redirect_to videos_url
        else
            render :new
        end 
    end
    
    def destroy
        @video = Video.find(params[:id])
        @video.destroy
        redirect_to videos_path
    end
    
    private 
    
    def video_params
        params.require(:video).permit(:link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/contacts/create.html.erb
<div class="margin">
<div class="center">
<h1>Thank you for your message!</h1>
<p>We'll get back to you soon!</p>
</div>
</div>

app/views/contacts/new.html.erb
<div class="margin">
<center>
<h1>Contact Us!</h1>
<p>Leave a Comment or Ask a Question!</p>

<%= form_for @contact do |f| %>
  <%= notice %>
  <%= @contact.errors.full_messages.join(', ') %>

  <%= f.text_field :name, placeholder: 'name' %>
  <%= f.email_field :email, placeholder: 'email' %>
  <%= f.text_area :message, placeholder: 'message' %>
  <%= f.submit 'Send' %>
<% end %>
</center>
</div>

app/views/images/_template.html.erb
<div class="back">
<%= link_to 'Back', :back %>
</div>

<% @images.each do |post| %>
<center>
    <%= link_to (image_tag post.i.url(:medium)), image_path(post) %>
  
    <div class="caption">
    <%= post.caption %>
    </div>
  
  
    <% if user_signed_in? and current_user.admin%>
      <%= link_to "Delete", image_path(post), class: "btn btn-danger", data: {:confirm => "Are you sure?"}, method: :delete %>
      <%= link_to "Edit Post", edit_image_path(post) %>
    <%end %>
  
 </center>
<% end %>

app/views/images/animal.html.erb
<div class="margin">
<div class="center">
<h1>Animals</h1>

<%= render "images/template" %>

</div>
</div>

app/views/images/cloud.html.erb
<div class="margin">
<div class="center">
<h1>Clouds</h1>

<%= render "images/template" %>

</div>
</div>

app/views/images/coast.html.erb
<div class="margin">
<div class="center">
<h1>Coastal Areas</h1>

<%= render "images/template" %>

</div>
</div>

app/views/images/edit.html.erb
<div class="margin">
<h1>Edit a Photo!</h1>

<div class="text-center">
  <%= image_tag @image.i.url(:medium) %>
</div>

<%= simple_form_for @image do |f| %>
  <%= f.input :i %>
  <%= f.input :caption %>
    <%= f.input :category, collection: ["Animals", "Flowers", "Sunrises/Sunsets", "Coastal Areas", "Lakes and Rivers", "Clouds", "Countryside", "Places", "Nature", "Portfolios"] %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/images/flower.html.erb
<div class="margin">
<div class="center">
<h1>Flowers</h1>

<%= render "images/template" %>

</div>
</div>

app/views/images/index.html.erb
<div class="margin">
<div class="center">
<div class="gal">
<h1>Gallery</h1>


<div class="imgLabels">
  <%= link_to 'Animals', "/animal" %>
  <%= link_to 'Flowers', "/flower" %>
  <%= link_to 'Sunrises and Sunsets', "/sun" %>
  <%= link_to 'Coastal Areas', "/coast" %>
  <%= link_to 'Lakes and Rivers', "/water" %>
  <%= link_to 'Clouds', "/cloud" %>
  <%= link_to 'Portfolios', "/portfolio" %>
</div>  
</div>

  <h1>All Photos</h1>
  <% @images.each do |post| %>
<center>
    <%= link_to (image_tag post.i.url(:medium)), image_path(post) %>
  
    <div class="caption">
    <%= post.caption %>
    </div>
  
  
    <% if user_signed_in? and current_user.admin%>
      <%= link_to "Delete", image_path(post), class: "btn btn-danger", data: {:confirm => "Are you sure?"}, method: :delete %>
      <%= link_to "Edit Post", edit_image_path(post) %>
    <%end %>
  
 </center>
<% end %>

</div>
</div>

app/views/images/new.html.erb
<div class="margin">
<h1>Sumbit a Photo!</h1>

<%= simple_form_for @image do |f| %>
  <%= f.input :i %>
  <%= f.input :caption %>
  <%= f.input :category, collection: ["Animals", "Flowers", "Sunrises/Sunsets", "Coastal Areas", "Lakes and Rivers", "Clouds", "Portfolios"] %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/images/portfolio.html.erb
<div class="margin">
<div class="center">
<h1>Portfolios</h1>

<%= render "images/template" %>

</div>
</div>

app/views/images/show.html.erb
<div class="margin">
<div class="center">
<div class="posts-wrapper row">
  <div class="post">
    <div class="post-head">
    </div>
    <div class="image center-block">
      <%= image_tag @image.i.url(:medium) %>
    </div>
    <p class="caption">
      <%= @image.caption %>
    </p>
    
    <div class="text-center">
      <%= link_to "Back", :back %>
    </div>
  </div>
</div>
</div>
</div>

app/views/images/sun.html.erb
<div class="margin">
<div class="center">
<h1>Sunrises and Sunsets</h1>

<%= render "images/template" %>

</div>
</div>

app/views/images/water.html.erb
<div class="margin">
<div class="center">
<h1>Lakes and Rivers</h1>

<%= render "images/template" %>

</div>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.input :body, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="margin">
<h2>Edit Post</h2>

<%= render "posts/form" %>
</div>

app/views/posts/index.html.erb
<div class="margin">
  <center><h1>News</h1></center>
    <div class="container">
  <div class="col-sm-10 col-sm-offset-1 col-xs-12 blog-content">
    <% @posts.each do |post| %>
    <div class="col-xs-12">
      <div class="text-center">
        <h2><%= post.title %></h2>
        <h6><%= post.created_at.strftime('%b %d, %Y') %></h6>
      </div>

      <div>
        <%= raw(post.body).truncate(358) %>
      </div>

      <div class="text-center">
        <%= link_to "READ MORE", post_path(post) %>
      </div>
          <% if user_signed_in? and current_user.admin%>
           <%= link_to "Edit", edit_post_path(post), class: "btn btn-default" %>
        <%= link_to "Delete", post_path(post), class: "btn btn-danger", data: {:confirm => "Are you sure?"}, method: :delete %>  
    <%end %>
      <br>
    </div>
    <% end %>
  </div>
</div>
</div>

app/views/posts/new.html.erb
<div class="margin">
<h2>Create New Post</h2>

<%= render "posts/form" %>
</div>

app/views/posts/show.html.erb
<div class="margin">
<div class="col-sm-11 col-xs-12 blog-content">
  <h2 class="text-center"><%= @post.title %></h2>
  <h5 class="text-center"><%= @post.created_at.strftime('%b %d, %Y') %></h5>
  <div><%= raw @post.body %></div>
  <%= link_to "Back", posts_path %>
</div>
</div>