config/routes.rb
Rails.application.routes.draw do
  resources 'contacts', only: [:new, :create], path_names: { new: '' }
  

  mount LetterOpenerWeb::Engine, at: "/letter_opener"

  mount Ckeditor::Engine => '/ckeditor'
  
  resources :events do
    get :get_events, on: :collection
  end
  devise_for :users
  
  get "/pages/:page" => "pages#show"
  
  get "/services" => "pages#services"
  
  root "pages#show", page: "home"
  
  resources :images
  
  get "/animal" => "images#animal"
  get "/flower" => "images#flower"
  get "/sun" => "images#sun"
  get "/coast" => "images#coast"
  get "/water" => "images#water"
  get "/cloud" => "images#cloud"
  get "/portfolio" => "images#portfolio"
  
  
  resources :videos, only: [:index, :new, :create, :destroy]
  
  resources :messages

  resources :posts
  
end

app/models/contact.rb
class Contact < MailForm::Base
  append :remote_ip, :user_agent
  attribute :name,      validate: true
  attribute :email,     validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  validates :message,   length: { in: 15..2000 }

  def headers
    {
      subject: 'Contact Form',
      to: 'edicristoforo@gmail.com',
      from: %("#{name}" <#{email}>)
    }
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
    validates :i, presence: true
    validates :caption, presence: true
    validates :category, presence: true

    
    has_attached_file :i, styles: {:medium => "640x" }
    validates_attachment_content_type :i, 
        :content_type => [/\Aimage\/.*\Z/, 'video/mp4']
    
    belongs_to :user
    
    
    
end

app/models/message.rb
class Message
    include ActiveModel::Model
    attr_accessor :name, :email, :body
    validates :name, :email, :body, presence: true
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
    validates :title, presence: true, length: {maximum: 140}
    validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  extend Devise::Models
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :posts, dependent: :destroy

end

app/models/video.rb
class Video < ActiveRecord::Base
    YT_LINK_FORMAT = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i
    validates :link, presence: true, format: YT_LINK_FORMAT
end

app/models/video_observer.rb
class VideoObserver < ActiveRecord::Observer
  def before_save(resource)
    video = Yt::Video.new url: resource.link
    resource.uid = video.id
    # resource.title = video.title
    # resource.likes = video.like_count
    # resource.dislikes = video.dislike_count
    # resource.published_at = video.published_at
  rescue Yt::Errors::NoItems
    resource.title = ''
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver 
      flash.now[:error] = nil
      flash.now[:notice] = 'Thank you for your message!'
    else
      flash.now[:error] = ' Cannot send message at this time'
      render :new
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
    
    def index
        @images = Image.all
    end
    
    # actions for every category
    def animal
        @images = Image.where(:category => "Animals")
    end
    
    def flower
        @images = Image.where(:category => "Flowers")
    end
    
    def sun
        @images = Image.where(:category => "Sunrises/Sunsets")
    end
    
    def coast
        @images = Image.where(:category => "Coastal Areas")
    end
        
    def water
        @images = Image.where(:category => "Lakes and Rivers")
    end
            
    def cloud
        @images = Image.where(:category => "Clouds")
    end
    
    def portfolio
        @images = Image.where(:category => "Portfolios")
    end
    

    
    def new
        @image = Image.new
    end
    
    def create
        @image = Image.create(post_params)
        
        if @image.save
            flash[:notice] = "Successfully created image!"
            redirect_to images_path
        else
            flash[:alert] = "Error creating new image!"
            render :new
        end
    end
    
    def destroy
        @image = Image.find(params[:id])
        @image.destroy
        redirect_to images_path
    end
    
    def show
        @image = Image.find(params[:id])
    end
    
    def edit
        @image = Image.find(params[:id])
    end
    
    def update 
        @image = Image.find(params[:id])
        @image.update(post_params)
        redirect_to(image_path(@image))
    end
    
    private 
    
    def post_params
        params.require(:image).permit(:i, :caption, :category)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def new
        @message = Message.new
    end

  def create
    @message = Message.new message_params

    if @message.valid?
      MessageMailer.contact_me(@message).deliver_now
      redirect_to new_message_url, notice: "Message received, thanks!"
    else
      flash[:notice] = "There was an error sending your message, please try again!"
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :body)
  end  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def show
        render template: "pages/#{params[:page]}"
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:edit, :update, :show, :delete]
    
    def index
        @posts = Post.all
    end
    
    def new 
        @post = Post.new
    end
    
    def create
        @post = Post.new(post_params)
        if @post.save
            flash[:notice] = "Successfully created post!"
            redirect_to post_path(@post)
        else
            flash[:alert] = "Error creating new post!"
            render :new
        end
    end
    
    def edit
    end
    
    def update
        if @post.update_attributes(post_params)
            flash[:notice] = "Successfully updated post!"
             redirect_to post_path(@posts)
        else
            flash[:alert] = "Error updating post!"
            render :edit
        end
    end
    
    def show
    end
    
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end
    
    private
    
    def post_params
        params.require(:post).permit(:title, :body)
    end
    
    def find_post 
        @post = Post.find(params[:id])
    end
    
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
    def index
        @videos = Video.order('created_at DESC')
    end

    def new
        @video = Video.new
    end

    def create
        @video = Video.new(video_params)
        if @video.save
            flash[:success] = 'Video added!'
            redirect_to videos_url
        else
            render :new
        end 
    end
    
    def destroy
        @video = Video.find(params[:id])
        @video.destroy
        redirect_to videos_path
    end
    
    private 
    
    def video_params
        params.require(:video).permit(:link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title">The following errors were found while submitting the form:</h3>
    </div>

    <div class="panel-body">
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header role="banner" class="app-header">
  <div id="main">
    <center>
  <div class="navbar">
    <%= link_to 'Home', "/" %>
    <%= link_to 'Gallery', "/images#index" %>
    <%= link_to 'Services', "/services" %>
    <%= link_to 'Place an Order', "" %>
    <%= link_to 'Contact Me', "/contacts" %>
    <%= link_to 'Blog', "/posts#index" %>
    
    
    <% if user_signed_in? and current_user.admin%>
        <!--This block is only visible to signed in admins -->
          <%= link_to 'New Photos', new_image_path %>
          <%= link_to 'New Post', new_post_path %>
          <%= link_to 'Check Mail', "/letter_opener" %>
          <%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
        <!-- The block ends here -->
    <% end %>
    
  </div>
  
  </center>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AnyTime Photography</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <script src="https://www.google.com/jsapi"></script>
  <script src="https://www.youtube.com/iframe_api"></script>

</head>
<body>
  
  <%= render "layouts/header" %>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<div class="home">
<div class="margin">
<div class="static-info">
    <div class="center">
        <h1>AnyTime Photography</h1>
        <h2>By Ruth DiCristoforo</h2>
    </div>
    
    <div class="row">
        <div class="column left">
            <h2>About AnyTime</h2>
            <p>Long example text. This is literally just to see how it will look when there is a lot of text. I hope it looks alright. I don't know what else to type. Is this enough text? Who knows! Hollywoo stars and celebrities, do they know things, what do they know, let's find out!</p>
        </div>
        <div class="column right">
            <h2>About Ruth</h2>
            <p>Bio here about Ruth, talk about how/why she started the photography business</p>
        </div>
    </div>
    
</div>
</div>
</div>

app/views/pages/services.html.erb
<div class="margin">
<h1>Services</h1>

<p>This is where the services will go!</p>
</div>